wip3

diff --git a/board/raspberrypi/rootfs_overlay/etc/init.d/S41udhcpd b/board/raspberrypi/rootfs_overlay/etc/init.d/S41udhcpd
--- a/board/raspberrypi/rootfs_overlay/etc/init.d/S41udhcpd
+++ b/board/raspberrypi/rootfs_overlay/etc/init.d/S41udhcpd
@@ -1,30 +1,43 @@
+#!/bin/sh
 DAEMON=/usr/sbin/udhcpd
 NAME=udhcpd
-DHCPD_OPTS="-S" # Additional options given to the server
+DHCPD_OPTS="/etc/udhcpd.conf" # Additional options given to the server
 
 test -x $DAEMON || exit 0
+touch /var/lib/misc/udhcpd.leases
+start() {
+    printf  "Starting $NAME: "
+    $DAEMON $DHCPD_OPTS
+#    umask 077
+#    start-stop-daemon -S -q -p --pidfile /var/run/$NAME.pid \
+#        --exec $DAEMON -- $DHCPD_OPTS
+#    [ $? = 0 ] && echo "OK" || echo "FAIL"
+}
+
+stop() {
+    printf  "Stopping $NAME: "
+#    umask 077
+#    start-stop-daemon -K -q -p /var/run/$NAME.pid \
+#    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    killall $NAME
+}
 
 case "$1" in
   start)
-    echo -n "Starting $NAME: "
-    start-stop-daemon --start --verbose --pidfile /var/run/$NAME.pid \
-        --oknodo --exec $DAEMON -- $DHCPD_OPTS
+    start
     ;;
   stop)
-    echo -n "Stopping $NAME: "
-    start-stop-daemon --stop --verbose --pidfile /var/run/$NAME.pid \
-        --oknodo --exec $DAEMON
+    stop
     ;;
   restart|force-reload)
-    $0 stop
+    stop
     sleep 1
-    $0 start    
+    start    
     ;;
   *)
-    N=/etc/init.d/$NAME
     echo "Usage: $N {start|stop|restart|force-reload}" >&2
     exit 1
     ;;
 esac
 
-exit 0
+exit $?
diff --git a/board/raspberrypi/rootfs_overlay/etc/init.d/S42hostapd b/board/raspberrypi/rootfs_overlay/etc/init.d/S42hostapd
--- a/board/raspberrypi/rootfs_overlay/etc/init.d/S42hostapd
+++ b/board/raspberrypi/rootfs_overlay/etc/init.d/S42hostapd
@@ -1,36 +1,44 @@
+#!/bin/sh
+
 DAEMON_SBIN=/usr/sbin/hostapd
-DAEMON_DEFS=/etc/default/hostapd
-DAEMON_CONF=/etc/hostapf.conf
+DAEMON_CONF=/etc/hostapd.conf
 NAME=hostapd
 PIDFILE=/var/run/hostapd.pid
 
 test -x "$DAEMON_SBIN"  || exit 0
-test -x "$DAEMON_CONF"  || exit 0
+test -r "$DAEMON_CONF"  || exit 0
 
 DAEMON_OPTS="-B -P $PIDFILE $DAEMON_OPTS $DAEMON_CONF"
 
+start() {
+    printf "Starting $NAME: "
+    umask 077
+    start-stop-daemon -S -q -p "$PIDFILE" \
+            --exec "$DAEMON_SBIN" -- $DAEMON_OPTS
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+}
 
+stop() {
+    printf "Stopping $NAME: "
+    start-stop-daemon -K -q -p "$PIDFILE" \
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+}
 case "$1" in
   start)
-    echo "Starting $NAME: "
-    start-stop-daemon --start --oknodo --quiet --exec "$DAEMON_SBIN" \
-        --pidfile "$PIDFILE" -- $DAEMON_OPTS >/dev/null
+    start
     ;;
   stop)
-    echo "Stopping $NAME: "
-    start-stop-daemon --stop --oknodo --quiet --exec "$DAEMON_SBIN" \
-        --pidfile "$PIDFILE"
+    stop
     ;;
   restart)
-    $0 stop
+    stop
     sleep 8
-    $0 start
+    start
     ;;
   *)
-    N=/etc/init.d/$NAME
     echo "Usage: $N {start|stop|restart}" >&2
     exit 1
     ;;
 esac
 
-exit 0
+exit $?
